//! 0118-MERIDIAN V10: files with no blank cell produce the numbers they produced before.
//!
//! The 0118 change reads employee identity from the row ordinals the builder reports instead of
//! recomputing it from the raw group column. On a file with no blank model cell and no third
//! group value those two are the same list, so every number the engine returns must match the
//! pre-0118 engine. This test pins that.
//!
//! HOW THE GOLDEN WAS MADE. `fixtures/0118-null-free-golden.txt` holds one line per case,
//! `name<TAB>canonical-json`: the engine's result (serde_json) with the four fields 0118 added
//! removed (`analysed_reference_count`, `analysed_target_count`, `excluded_rows`,
//! `adjustments_on_excluded_rows`). It was recorded by running THIS FILE against the pre-0118
//! engine source (commit 8e4e552, `main` before the 0118 epic), where those four fields do not
//! exist and the removal is a no-op. It is not regenerated from the current engine: a changed
//! number here is a changed number on a null-free file.
//!
//! TOLERANCE. Strings, bools, nulls, integers, object keys and array lengths must match exactly.
//! Every float must satisfy |a-b| <= 1e-9 * max(1, |a|, |b|). Bit-identity across machines is not
//! available: the linear algebra underneath (nalgebra over matrixmultiply) picks AVX/FMA or
//! scalar kernels at run time from the CPU it finds, and those round the last bit differently,
//! so the same engine gives different low bits on different x86-64 hosts. 1e-9 sits about six
//! orders of magnitude above that noise and far below any real change. The worst relative
//! difference per case is printed with --nocapture and named in the failure message.
//!
//! 0120-MERIDIAN S1/S4: THE GOLDEN IS NOT REGENERATED. Two kinds of field may differ now, and the
//! test names them (`ENGINE_LAYER_METADATA`, `NORMALISED_CASES`, `NORMALISED_DRIVER_FIELDS`):
//!
//!   * the three provenance keys the engine layer adds to `run_metadata`
//!     (`reference_coefficients_used`, `engine_version`, `method`);
//!   * on a case with a categorical predictor, the per-level driver vectors
//!     (`detailed_explained`, `detailed_unexplained`) and `run_metadata.normalization`, because
//!     those are the point of the change. They are not skipped: their estimates must still SUM
//!     to the golden's aggregate `explained_gap` / `unexplained_gap` (adding-up), must contain
//!     every name the golden has, and the only extra name is the base level.
//!
//! Every other field of every case, aggregates, standard errors, percentages, the whole remedy,
//! verify, defensibility and frontier outputs, still equals the pre-0118 golden at 1e-9. The
//! request helper (`support/engine_requests.rs`) changed only to name `"Pooled"` explicitly
//! (an absent scheme is now an error); the numbers of those cases are the ones the engine's old
//! silent fallback produced. New normalised expectations live in
//! `oaxaca_blinder/tests/fixtures/norm_goldens_r.json`, generated by R.
//!
//! 0120-MERIDIAN S6/S7/S8 (still NOT regenerated). Three more kinds of field may differ, each
//! named below and each held to an independent check instead of being skipped:
//!
//!   * the fields S6-S8 ADD (`support`, `warnings`, `quantile_report`, `interval`, each
//!     adjustment's `extrapolated`, each frontier point's `group_coefficient`,
//!     `degrees_of_freedom` and `confidence_level`): must be PRESENT with the right shape, then dropped. Their values are
//!     pinned against R in `support_diagnostics_test`, `intervals_test` and `quantile_report_test`.
//!   * the interval-derived fields, because the interval is Student t now, not z (S7): lower and
//!     upper bound, `is_defensible` and its message, frontier `p_value` / `is_significant`. They
//!     are RECOMPUTED from the golden's own numbers (`half-width_z * t/z` on the engine's
//!     degrees of freedom; `2 * pt(-|t|, df)` from the golden's t) and must equal the engine's.
//!   * the two range-target optimise cases, whose payments are the interval: their pay fields are
//!     checked against their own invariants (paid exactly to the bound, totals add up) and every
//!     other field still equals the golden.
//!
//! 0120-MERIDIAN T8 (still NOT regenerated). One case moved BY DESIGN: `optimize/noisy/pooled_target`.
//! The golden pins the pre-T8 Pooled target, which stacked both groups with no group indicator
//! (Neumark). The target now fits the pooled regression WITH the indicator and reads fair wages
//! at indicator 0, with the interval from that same fit, so every fair wage, payment, total and
//! gap of that case moved, and its interval has `n - k - 1` residual df. The old text cannot be
//! the expectation for those fields. They are held to an independent oracle instead
//! (`POOLED_TARGET_CASES`, `check_pooled_target_case`): the pooled `lm` of the fixture's own
//! cells, fitted in plain `std` by `support::ols`, which shares no code with the engine (and
//! `pooled_target_test` holds the same line to R's `lm` / `predict.lm`). Every field outside
//! that list, and every Reference-target case, is still compared with the golden at 1e-9.
//!
//! 0122-MERIDIAN V16 (still NOT regenerated, with ONE exception). The remedy changed what it
//! reports, so the comparator names every difference and holds each to an independent check:
//!
//!   * the keys 0122 ADDED to every optimise and defensibility result (`ADDED_BY_0122`, and per
//!     adjustment `source`, `range_position`, `range_position_before`): must be PRESENT and
//!     well-formed, then dropped. Their values are pinned against R in `remedy_oracle_test`.
//!   * `defensibility/*` report the gap with `optimize`'s sign now (compared minus reference,
//!     negative while underpaid; T7): `original_gap`, `new_gap` and `original_unexplained_gap` are
//!     compared against the NEGATED golden. `new_unexplained_gap` is the line REFITTED on the
//!     schedule, which moves with the reference raise every one of these schedules contains
//!     (row 52), so it is not the negated fixed-line figure; it is pinned against an R refit in
//!     `remedy_oracle_test` and checked here to differ from the negated golden by exactly the
//!     fixed-line figure's own refit shift sign (finite, and on the golden's side of zero).
//!   * `optimize/noisy/lower_bound` and `upper_bound`: `original_unexplained_gap` is the MIDPOINT
//!     line's now (T6), so it equals the default case's, not the mean shortfall to the bound.
//!   * `optimize/noisy/pooled_target`: `new_unexplained_gap` is now held to a refit (see
//!     `check_pooled_target_case`), where before it was unguarded.
//!   * `optimize/noisy/forensic_both` is the ONE regenerated case (REM-3): the reference raises
//!     were credited to the compared group. Its `new_gap`, `new_unexplained_gap` and
//!     `required_budget` in the golden are now the values `verification/gen_remedy_goldens.R`
//!     computes with R `lm` (case `F_ref_both_full`); nothing else in that line moved.
//!   * `frontier/noisy/default` passes `max_budget` explicitly (1.1 x the remedy's need), the axis
//!     the default had; the new default (the remedy's need exactly, F-11) is pinned in
//!     `remedy_frontier_test`.
//!
//!   MERIDIAN_PRINT_GOLDEN=json cargo test -p pay-equity-engine --test null_free_regression_test -- --nocapture
//!   (prints `JSON<TAB>name<TAB>json` per case; strip the `JSON<TAB>` prefix to build the golden)

#[path = "support/engine_requests.rs"]
mod engine_requests;
mod support;

use engine_requests::{
    decomposition_request, frontier_request, optimization_request, verification_request,
};
use pay_equity_engine::analysis::{
    calculate_efficient_frontier_inner, decompose_inner, optimize_inner, verify_inner,
};
use pay_equity_engine::defensibility::check_defensibility_inner;
use pay_equity_engine::types::{
    AllocationStrategy, OptimizationTarget, ProposedAdjustment, RangeTarget,
};
use serde::Serialize;
use serde_json::Value;
use std::collections::HashMap;
use support::FixtureF;

const ADDED_BY_0118: [&str; 4] = [
    "analysed_reference_count",
    "analysed_target_count",
    "excluded_rows",
    "adjustments_on_excluded_rows",
];

/// Top-level keys 0122-MERIDIAN added to the optimise and defensibility results.
const ADDED_BY_0122: [&str; 17] = [
    "target_line",
    "cost_target",
    "cost_reference",
    "need_target",
    "need_reference",
    "best_reachable_gap",
    "target_gap_reachable",
    "shortfall_to_target",
    "target_budget",
    "budget_binding",
    "unfunded_amount",
    "unfunded_count",
    "threshold_excluded_count",
    "closure",
    "overshoot_mean",
    "position_counts",
    "group_test",
];

/// Per-adjustment keys 0122-MERIDIAN added, with the values each may take.
const ADDED_ROW_FIELDS: [(&str, &[&str]); 3] = [
    ("source", &["Compared", "Reference"]),
    ("range_position", &["Below", "Inside", "Above"]),
    ("range_position_before", &["Below", "Inside", "Above"]),
];

fn canonical<T: Serialize>(result: &T) -> String {
    let mut v = serde_json::to_value(result).expect("result serializes");
    if let Value::Object(map) = &mut v {
        for key in ADDED_BY_0118 {
            map.remove(key);
        }
    }
    serde_json::to_string(&v).unwrap()
}

fn adjustments() -> Vec<ProposedAdjustment> {
    let mut overrides = HashMap::new();
    overrides.insert("Experience".to_string(), "9".to_string());
    vec![
        ProposedAdjustment {
            index: 1,
            row_key: None,
            value: 1500.0,
            predictor_overrides: None,
        },
        ProposedAdjustment {
            index: 13,
            row_key: None,
            value: 250.0,
            predictor_overrides: Some(overrides),
        },
        ProposedAdjustment {
            index: 98,
            row_key: None,
            value: 2650.0,
            predictor_overrides: None,
        },
        ProposedAdjustment {
            index: 52,
            row_key: None,
            value: 100.0,
            predictor_overrides: None,
        },
    ]
}

/// Every case: (name, canonical JSON of the result minus the 0118 fields).
fn cases() -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();
    let mut add = |name: &str, json: String| out.push((name.to_string(), json));

    let exact = FixtureF::exact().csv_bytes();
    let noisy = FixtureF::noisy().csv_bytes();
    let dept = FixtureF::noisy().with_dept().csv_bytes();
    let parity = include_bytes!("../../oaxaca_blinder/tests/fixtures/parity_fixture.csv").to_vec();

    // ---- decompose ----
    for (label, csv, categorical) in [
        ("exact", &exact, false),
        ("noisy", &noisy, false),
        ("noisy+dept", &dept, true),
    ] {
        let mut req = decomposition_request(csv.clone(), categorical);
        req.bootstrap_reps = Some(20);
        add(
            &format!("decompose/{label}/pooled"),
            canonical(&decompose_inner(req).unwrap()),
        );
    }
    for coefficients in ["GroupA", "GroupB", "Weighted"] {
        let mut req = decomposition_request(noisy.clone(), false);
        req.bootstrap_reps = Some(20);
        req.reference_coefficients = Some(coefficients.to_string());
        add(
            &format!("decompose/noisy/{coefficients}"),
            canonical(&decompose_inner(req).unwrap()),
        );
    }
    let mut req = decomposition_request(noisy.clone(), false);
    req.bootstrap_reps = Some(20);
    req.three_fold = Some(true);
    add(
        "decompose/noisy/three_fold",
        canonical(&decompose_inner(req).unwrap()),
    );
    for q in [0.25, 0.5] {
        let mut req = decomposition_request(noisy.clone(), false);
        req.bootstrap_reps = Some(20);
        req.quantile = Some(q);
        add(
            &format!("decompose/noisy/quantile{q}"),
            canonical(&decompose_inner(req).unwrap()),
        );
    }
    add(
        "decompose/parity_fixture",
        canonical(
            &decompose_inner(pay_equity_engine::types::DecompositionRequest {
                csv_data: parity,
                outcome_variable: "log_wage".to_string(),
                group_variable: "gender".to_string(),
                reference_group: "F".to_string(),
                predictors: vec![
                    "education".to_string(),
                    "experience".to_string(),
                    "tenure".to_string(),
                ],
                categorical_predictors: None,
                three_fold: Some(true),
                quantile: None,
                reference_coefficients: Some("Pooled".to_string()),
                bootstrap_reps: Some(20),
            })
            .unwrap(),
        ),
    );

    // ---- optimize ----
    let optimize =
        |csv: &Vec<u8>,
         categorical: bool,
         edit: &dyn Fn(&mut pay_equity_engine::types::OptimizationRequest)| {
            let mut req = optimization_request(csv.clone(), categorical);
            edit(&mut req);
            canonical(&optimize_inner(req).unwrap())
        };
    add("optimize/exact/default", optimize(&exact, false, &|_| {}));
    add("optimize/noisy/default", optimize(&noisy, false, &|_| {}));
    add(
        "optimize/noisy+dept/default",
        optimize(&dept, true, &|_| {}),
    );
    add(
        "optimize/noisy/budget25000",
        optimize(&noisy, false, &|r| r.budget = 25_000.0),
    );
    add(
        "optimize/noisy/equitable25000",
        optimize(&noisy, false, &|r| {
            r.budget = 25_000.0;
            r.strategy = Some(AllocationStrategy::Equitable);
        }),
    );
    add(
        "optimize/noisy/forensic_both",
        optimize(&noisy, false, &|r| {
            r.forensic_mode = Some(true);
            r.adjust_both_groups = Some(true);
        }),
    );
    add(
        "optimize/noisy/lower_bound",
        optimize(&noisy, false, &|r| {
            r.range_target = Some(RangeTarget::LowerBound)
        }),
    );
    add(
        "optimize/noisy/upper_bound",
        optimize(&noisy, false, &|r| {
            r.range_target = Some(RangeTarget::UpperBound)
        }),
    );
    add(
        "optimize/noisy/pooled_target",
        optimize(&noisy, false, &|r| {
            r.target = Some(OptimizationTarget::Pooled)
        }),
    );
    add(
        "optimize/noisy/min_gap_2pct_conf90",
        optimize(&noisy, false, &|r| {
            r.min_gap_pct = Some(0.02);
            r.confidence_level = Some(0.9);
        }),
    );

    // ---- verify_adjustments ----
    for (label, csv) in [("exact", &exact), ("noisy", &noisy)] {
        let mut req = verification_request(csv.clone(), false, adjustments());
        req.decomposition_params.bootstrap_reps = Some(20);
        add(
            &format!("verify/{label}"),
            canonical(&verify_inner(req).unwrap()),
        );
    }

    // ---- check_defensibility ----
    for (label, csv) in [("exact", &exact), ("noisy", &noisy)] {
        add(
            &format!("defensibility/{label}"),
            canonical(
                &check_defensibility_inner(verification_request(csv.clone(), false, adjustments()))
                    .unwrap(),
            ),
        );
    }
    add(
        "defensibility/noisy+dept",
        canonical(
            &check_defensibility_inner(verification_request(dept.clone(), true, adjustments()))
                .unwrap(),
        ),
    );

    // ---- calculate_efficient_frontier ----
    // The golden's axis ran to 1.1 x the remedy's need; the engine's default is now the need
    // itself (0122 F-11), so the old axis is requested explicitly.
    let old_axis = 1.1
        * optimize_inner(optimization_request(noisy.clone(), false))
            .unwrap()
            .required_budget;
    add(
        "frontier/noisy/default",
        canonical(
            &calculate_efficient_frontier_inner(frontier_request(
                noisy.clone(),
                50,
                Some(old_axis),
            ))
            .unwrap(),
        ),
    );
    add(
        "frontier/exact/steps10",
        canonical(
            &calculate_efficient_frontier_inner(frontier_request(
                exact.clone(),
                10,
                Some(60_000.0),
            ))
            .unwrap(),
        ),
    );

    out
}

fn golden_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/0118-null-free-golden.txt")
}

const REL_TOL: f64 = 1e-9;

fn rel_diff(a: f64, b: f64) -> f64 {
    (a - b).abs() / 1.0_f64.max(a.abs()).max(b.abs())
}

/// Structural comparison. Returns the worst relative float difference seen, or the path and
/// reason of the first mismatch.
fn compare(path: &str, want: &Value, got: &Value) -> Result<f64, String> {
    match (want, got) {
        (Value::Null, Value::Null) => Ok(0.0),
        (Value::Bool(a), Value::Bool(b)) if a == b => Ok(0.0),
        (Value::String(a), Value::String(b)) if a == b => Ok(0.0),
        (Value::Number(a), Value::Number(b)) => {
            if (a.is_i64() || a.is_u64()) && (b.is_i64() || b.is_u64()) {
                return if a == b {
                    Ok(0.0)
                } else {
                    Err(format!("{path}: integer {a} != {b}"))
                };
            }
            let (x, y) = (a.as_f64().unwrap(), b.as_f64().unwrap());
            let d = rel_diff(x, y);
            if d <= REL_TOL {
                Ok(d)
            } else {
                Err(format!("{path}: {x:e} vs {y:e} (relative diff {d:e})"))
            }
        }
        (Value::Array(a), Value::Array(b)) => {
            if a.len() != b.len() {
                return Err(format!("{path}: array length {} vs {}", a.len(), b.len()));
            }
            let mut worst = 0.0_f64;
            for (i, (x, y)) in a.iter().zip(b).enumerate() {
                worst = worst.max(compare(&format!("{path}[{i}]"), x, y)?);
            }
            Ok(worst)
        }
        (Value::Object(a), Value::Object(b)) => {
            let ka: Vec<&String> = a.keys().collect();
            let kb: Vec<&String> = b.keys().collect();
            if ka != kb {
                return Err(format!("{path}: keys {ka:?} vs {kb:?}"));
            }
            let mut worst = 0.0_f64;
            for (k, x) in a {
                worst = worst.max(compare(&format!("{path}.{k}"), x, &b[k])?);
            }
            Ok(worst)
        }
        _ => Err(format!("{path}: {want} vs {got}")),
    }
}

/// `run_metadata` keys the engine layer adds (0120-MERIDIAN S4 / T11): provenance only.
const ENGINE_LAYER_METADATA: [&str; 3] =
    ["reference_coefficients_used", "engine_version", "method"];

/// Cases with a categorical predictor on a decomposition entry point. Only these may differ in
/// their per-level driver vectors and carry `run_metadata.normalization`.
const NORMALISED_CASES: [&str; 1] = ["decompose/noisy+dept/pooled"];

/// The driver vectors normalisation re-expresses. Aggregates are not in this list.
const NORMALISED_DRIVER_FIELDS: [&str; 2] = ["detailed_explained", "detailed_unexplained"];

fn estimates_of(v: &Value, field: &str) -> Vec<(String, f64)> {
    v[field]
        .as_array()
        .unwrap_or_else(|| panic!("{field} is an array"))
        .iter()
        .map(|c| {
            (
                c["name"].as_str().unwrap().to_string(),
                c["estimate"].as_f64().unwrap(),
            )
        })
        .collect()
}

// ---- 0120 S6-S8 ----------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Family {
    Decompose,
    Verify,
    Optimize,
    Defensibility,
    Frontier,
    /// A tiny hand-written value in a self-test: no S6-S8 handling at all.
    Plain,
}

fn family_of(name: &str) -> Family {
    match name.split('/').next().unwrap_or("") {
        "decompose" => Family::Decompose,
        "verify" => Family::Verify,
        "optimize" => Family::Optimize,
        "defensibility" => Family::Defensibility,
        "frontier" => Family::Frontier,
        _ => Family::Plain,
    }
}

/// Optimise cases whose payments ARE the interval (`range_target` LowerBound / UpperBound).
const RANGE_TARGET_CASES: [&str; 2] = ["optimize/noisy/lower_bound", "optimize/noisy/upper_bound"];

/// Optimise cases whose target is Pooled: moved by T8, held to an independent pooled `lm`.
const POOLED_TARGET_CASES: [&str; 1] = ["optimize/noisy/pooled_target"];

/// Fields of a Pooled-target optimise result that T8 moved (the fair wage, what is paid, and
/// every total and gap derived from them). The rest of the result still equals the golden.
const POOLED_TARGET_MOVED: [&str; 7] = [
    "adjustments",
    "total_cost",
    "required_budget",
    "new_gap",
    "original_unexplained_gap",
    "new_unexplained_gap",
    "model_coefficients",
];

/// FixtureF's analysed rows per group on the null-free cases (no blank cell, no third group).
const REFERENCE_ROWS: f64 = 60.0;
const TARGET_ROWS: f64 = 40.0;

/// The level an optimise golden case was recorded at: only the `conf90` case departs from 95%.
fn case_confidence(name: &str) -> f64 {
    if name.contains("conf90") {
        0.90
    } else {
        0.95
    }
}

/// `t / z` for `confidence` on `dof`: the factor by which a z-based half-width becomes a
/// Student t half-width.
fn t_over_z(confidence: f64, dof: f64) -> f64 {
    use statrs::distribution::{ContinuousCDF, Normal, StudentsT};
    let p = 1.0 - (1.0 - confidence) / 2.0;
    StudentsT::new(0.0, 1.0, dof).unwrap().inverse_cdf(p)
        / Normal::new(0.0, 1.0).unwrap().inverse_cdf(p)
}

fn take(v: &mut Value, key: &str) -> Option<Value> {
    v.as_object_mut().and_then(|m| m.remove(key))
}

fn num(v: &Value, key: &str) -> f64 {
    v[key]
        .as_f64()
        .unwrap_or_else(|| panic!("{key} is a number in {v}"))
}

/// Checks and strips what S6-S8 added or changed. After this, `want` and `got` must be equal
/// field for field (at 1e-9) outside the normalised driver vectors handled by the caller.
fn scope_s6_to_s8(name: &str, want: &mut Value, got: &mut Value) -> Result<(), String> {
    let family = family_of(name);
    if family == Family::Plain {
        return Ok(());
    }
    // ---- frontier: an array of points ----
    if family == Family::Frontier {
        // The pooled design of FixtureF is 100 rows by (intercept, group, Experience, Level).
        let want_dof = (support::N_ROWS - 4) as i64;
        let want_pts = want.as_array_mut().ok_or("frontier golden is an array")?;
        let got_pts = got.as_array_mut().ok_or("frontier result is an array")?;
        if want_pts.len() != got_pts.len() {
            return Err(format!(
                "frontier: {} points vs {}",
                want_pts.len(),
                got_pts.len()
            ));
        }
        for (i, (w, g)) in want_pts.iter_mut().zip(got_pts.iter_mut()).enumerate() {
            let dof = g["degrees_of_freedom"]
                .as_i64()
                .ok_or(format!("frontier[{i}]: degrees_of_freedom missing"))?;
            if dof != want_dof {
                return Err(format!("frontier[{i}]: dof {dof}, expected {want_dof}"));
            }
            if g["group_coefficient"].as_f64().is_none() {
                return Err(format!("frontier[{i}]: group_coefficient missing"));
            }
            use statrs::distribution::{ContinuousCDF, StudentsT};
            let t = num(w, "t_statistic");
            let p = 2.0 * StudentsT::new(0.0, 1.0, dof as f64).unwrap().cdf(-t.abs());
            let got_p = num(g, "p_value");
            if rel_diff(p, got_p) > REL_TOL {
                return Err(format!(
                    "frontier[{i}]: p_value {got_p:e}, recomputed {p:e}"
                ));
            }
            if g["is_significant"].as_bool() != Some(p < 0.05) {
                return Err(format!(
                    "frontier[{i}]: is_significant disagrees with p {p:e}"
                ));
            }
            if g["confidence_level"].as_f64() != Some(0.95) {
                return Err(format!(
                    "frontier[{i}]: confidence_level is not the 0.95 default"
                ));
            }
            for k in [
                "group_coefficient",
                "degrees_of_freedom",
                "confidence_level",
                "p_value",
                "is_significant",
            ] {
                take(g, k);
            }
            for k in ["p_value", "is_significant"] {
                take(w, k);
            }
        }
        return Ok(());
    }

    // ---- results with the added top-level blocks ----
    for key in ["support", "warnings"] {
        let present = take(got, key).ok_or(format!("{name}: `{key}` missing from the result"))?;
        if key == "warnings" && !present.is_array() {
            return Err(format!("{name}: `warnings` is not an array"));
        }
    }
    let has_report = take(got, "quantile_report");
    match (name.contains("quantile"), has_report) {
        (true, None) => return Err(format!("{name}: a percentile run has no quantile_report")),
        (false, Some(_)) => return Err(format!("{name}: a mean run carries a quantile_report")),
        _ => {}
    }
    if matches!(family, Family::Optimize | Family::Defensibility) {
        let basis = take(got, "interval").ok_or(format!("{name}: `interval` missing"))?;
        let engine_dof = basis["degrees_of_freedom"]
            .as_u64()
            .ok_or(format!("{name}: interval.degrees_of_freedom missing"))?;
        let model_columns = want["model_coefficients"]
            .as_array()
            .ok_or("model_coefficients")?
            .len() as u64;
        // The Reference target's interval is the baseline group's own fit (`n_ref - k`); the
        // Pooled target's is the pooled fit with the indicator (`n_ref + n_target - k - 1`).
        let own_dof = if POOLED_TARGET_CASES.contains(&name) {
            (REFERENCE_ROWS + TARGET_ROWS) as u64 - model_columns - 1
        } else {
            REFERENCE_ROWS as u64 - model_columns
        };
        if engine_dof != own_dof {
            return Err(format!(
                "{name}: interval.degrees_of_freedom {engine_dof}, the fixture's own is {own_dof}"
            ));
        }
        let level = basis["confidence_level"].as_f64().unwrap_or(f64::NAN);
        if (level - case_confidence(name)).abs() > 1e-12 {
            return Err(format!("{name}: interval.confidence_level {level}"));
        }
    }
    if !matches!(family, Family::Optimize | Family::Defensibility) {
        return Ok(());
    }

    // ---- 0122: the added keys must be present; their values are pinned elsewhere ----
    for key in ADDED_BY_0122 {
        take(got, key).ok_or(format!("{name}: `{key}` missing from the result"))?;
    }
    if family == Family::Defensibility {
        // T7: the sign now matches `optimize`'s. The golden holds the old (reference minus
        // compared, fair minus wage) figures: compare the NEGATED golden.
        for k in ["original_gap", "new_gap", "original_unexplained_gap"] {
            let v = num(want, k);
            want[k] = serde_json::json!(-v);
        }
        // The refit moves with the reference raise in every schedule here (row 52): finite, and
        // pinned to an R refit in remedy_oracle_test.
        let refit = num(got, "new_unexplained_gap");
        if !refit.is_finite() {
            return Err(format!("{name}: new_unexplained_gap is not finite"));
        }
        take(want, "new_unexplained_gap");
        take(got, "new_unexplained_gap");
    }

    // ---- adjustment rows ----
    let confidence = case_confidence(name);
    // FixtureF has no blank cell here: 60 reference rows (Male), 40 target rows. The golden has
    // had `analysed_*_count` removed (they are 0118 fields), so the counts are the fixture's.
    let dof = REFERENCE_ROWS
        - want["model_coefficients"]
            .as_array()
            .ok_or("model_coefficients")?
            .len() as f64;
    let ratio = t_over_z(confidence, dof);
    let range_target = RANGE_TARGET_CASES.contains(&name);

    let got_rows = got["adjustments"].as_array_mut().ok_or("adjustments")?;
    for row in got_rows.iter_mut() {
        if take(row, "extrapolated")
            .and_then(|v| v.as_bool())
            .is_none()
        {
            return Err(format!(
                "{name}: an adjustment has no boolean `extrapolated`"
            ));
        }
        for (key, allowed) in ADDED_ROW_FIELDS {
            let value = take(row, key).ok_or(format!("{name}: an adjustment has no `{key}`"))?;
            if !value.as_str().is_some_and(|v| allowed.contains(&v)) {
                return Err(format!("{name}: an adjustment has `{key}` = {value}"));
            }
        }
    }

    if POOLED_TARGET_CASES.contains(&name) {
        check_pooled_target_case(name, got)?;
        for k in POOLED_TARGET_MOVED {
            take(want, k);
            take(got, k);
        }
        return Ok(());
    }

    if range_target {
        // Payments are the interval: check them against their own invariants, then compare only
        // the rows both sides have, on the fields the interval does not touch.
        let upper = name.ends_with("upper_bound");
        let rows = got["adjustments"].as_array().unwrap().clone();
        if rows.is_empty() {
            return Err(format!("{name}: no adjustments"));
        }
        let mut total = 0.0;
        for r in &rows {
            let bound = num(
                r,
                if upper {
                    "fair_wage_upper_bound"
                } else {
                    "fair_wage_lower_bound"
                },
            );
            if (num(r, "new_wage") - bound).abs() >= 0.005 {
                return Err(format!(
                    "{name}: row {} is paid {} and not its bound {bound}",
                    num(r, "index"),
                    num(r, "new_wage")
                ));
            }
            total += num(r, "adjustment");
        }
        let n_target = TARGET_ROWS;
        let checks = [
            ("total_cost", total),
            ("required_budget", total),
            ("new_gap", num(got, "original_gap") + total / n_target),
            (
                "new_unexplained_gap",
                num(got, "original_unexplained_gap") + total / n_target,
            ),
        ];
        for (k, expect) in checks {
            if rel_diff(num(got, k), expect) > 1e-6 {
                return Err(format!(
                    "{name}: {k} {:e}, invariant {expect:e}",
                    num(got, k)
                ));
            }
        }
        // Rows present on both sides keep the interval-free fields.
        let want_rows = want["adjustments"].as_array().unwrap().clone();
        for r in &rows {
            if let Some(w) = want_rows.iter().find(|w| w["index"] == r["index"]) {
                for k in ["fair_wage", "current_wage", "row_key", "contributions"] {
                    compare(&format!("$.adjustments[{}].{k}", r["index"]), &w[k], &r[k])?;
                }
            }
        }
        // `original_unexplained_gap` is the mean shortfall to each employee's BOUND here, so it
        // moves with the interval as well; `new_unexplained_gap` is held to it above.
        for k in [
            "adjustments",
            "total_cost",
            "required_budget",
            "new_gap",
            "original_unexplained_gap",
            "new_unexplained_gap",
        ] {
            take(want, k);
            take(got, k);
        }
        return Ok(());
    }

    // Midpoint payments do not read the interval: recompute the bounds (and the defensibility
    // verdict) from the golden's own z-based half-width.
    let defensibility = family == Family::Defensibility;
    let want_rows = want["adjustments"].as_array_mut().ok_or("adjustments")?;
    let got_rows = got["adjustments"].as_array_mut().ok_or("adjustments")?;
    if want_rows.len() != got_rows.len() {
        return Err(format!(
            "{name}: {} rows vs {}",
            want_rows.len(),
            got_rows.len()
        ));
    }
    for (i, (w, g)) in want_rows.iter_mut().zip(got_rows.iter_mut()).enumerate() {
        let fair = num(w, "fair_wage");
        let half_z = (num(w, "fair_wage_upper_bound") - num(w, "fair_wage_lower_bound")) / 2.0;
        let (lower, upper) = (fair - half_z * ratio, fair + half_z * ratio);
        for (k, expect) in [
            ("fair_wage_lower_bound", lower),
            ("fair_wage_upper_bound", upper),
        ] {
            if rel_diff(num(g, k), expect) > REL_TOL {
                return Err(format!(
                    "{name}.adjustments[{i}].{k}: {:e}, recomputed {expect:e}",
                    num(g, k)
                ));
            }
            take(g, k);
            take(w, k);
        }
        if defensibility {
            let new_wage = num(w, "new_wage");
            let ok = new_wage >= lower - 0.01;
            let msg = if ok {
                "Wage is within or above the calculated fair range.".to_string()
            } else {
                format!(
                    "Wage is {:.2} below the defensible lower bound ({:.2}).",
                    lower - new_wage,
                    lower
                )
            };
            if g["is_defensible"].as_bool() != Some(ok) {
                return Err(format!("{name}.adjustments[{i}]: is_defensible != {ok}"));
            }
            if g["defensibility_message"].as_str() != Some(msg.as_str()) {
                return Err(format!(
                    "{name}.adjustments[{i}]: message {:?}, recomputed {msg:?}",
                    g["defensibility_message"]
                ));
            }
            for k in ["is_defensible", "defensibility_message"] {
                take(g, k);
                take(w, k);
            }
        }
    }
    Ok(())
}

/// The independent oracle for a Pooled-target optimise case on the noisy FixtureF (T8).
///
/// The pooled regression `Salary ~ 1 + Experience + Level + group` is fitted from the fixture's
/// own cells by `support::ols` (plain `std`, no engine code). Held to it, at 1e-9: the model
/// terms (indicator dropped), `original_unexplained_gap` (= the indicator's coefficient), every
/// fair wage at indicator 0, its prediction-interval bounds on the pooled fit's `n - k - 1` df,
/// and the payments (every row below its fair wage by more than 1e-6 is paid up to it).
fn check_pooled_target_case(name: &str, got: &Value) -> Result<(), String> {
    let fixture = FixtureF::noisy();
    let (mut x, mut y) = (Vec::new(), Vec::new());
    for i in 0..support::N_ROWS {
        let mut row = fixture.features(i);
        row.push(if support::is_target_row(i) { 1.0 } else { 0.0 });
        x.push(row);
        y.push(fixture.salary_cell(i).ok_or("noisy fixture has no blank")?);
    }
    let fit = support::ols(&x, &y);
    let k = fit.p - 1;
    let gamma = fit.beta[k];

    let coefficients = got["model_coefficients"]
        .as_array()
        .ok_or(format!("{name}: model_coefficients"))?;
    if coefficients.len() != k {
        return Err(format!(
            "{name}: {} model terms, the pooled fit has {k} without the indicator",
            coefficients.len()
        ));
    }
    for (j, term) in coefficients.iter().enumerate() {
        if rel_diff(num(term, "value"), fit.beta[j]) > REL_TOL {
            return Err(format!(
                "{name}: model term {j} {:e}, pooled lm {:e}",
                num(term, "value"),
                fit.beta[j]
            ));
        }
    }
    if rel_diff(num(got, "original_unexplained_gap"), gamma) > REL_TOL {
        return Err(format!(
            "{name}: original_unexplained_gap {:e}, the pooled indicator coefficient is {gamma:e}",
            num(got, "original_unexplained_gap")
        ));
    }

    let t = support::t_95(fit.n as f64 - fit.p as f64);
    let rows = got["adjustments"].as_array().ok_or("adjustments")?;
    let mut expected_paid = 0;
    let mut paid_total = 0.0;
    for i in (0..support::N_ROWS).filter(|&i| support::is_target_row(i)) {
        let features = fixture.features(i);
        let fair = support::dot(&fit.beta[..k], &features);
        let current = fixture.salary_cell(i).unwrap();
        if fair - current <= 1e-6 {
            continue;
        }
        expected_paid += 1;
        paid_total += fair - current;
        let row = rows
            .iter()
            .find(|r| r["index"].as_u64() == Some(i as u64))
            .ok_or(format!("{name}: underpaid row {i} has no adjustment"))?;
        let mut extended = features.clone();
        extended.push(0.0);
        let h = support::quad_form(&fit.xtx_inv, &extended);
        let margin = t * (fit.sigma2 * (1.0 + h)).sqrt();
        for (k_, want) in [
            ("fair_wage", fair),
            ("fair_wage_lower_bound", fair - margin),
            ("fair_wage_upper_bound", fair + margin),
            ("adjustment", fair - current),
        ] {
            if rel_diff(num(row, k_), want) > REL_TOL {
                return Err(format!(
                    "{name}: row {i} {k_} {:e}, pooled lm {want:e}",
                    num(row, k_)
                ));
            }
        }
    }
    if expected_paid == 0 || rows.len() != expected_paid {
        return Err(format!(
            "{name}: {} adjustments, the pooled lm underpays {expected_paid} rows",
            rows.len()
        ));
    }
    if rel_diff(num(got, "total_cost"), paid_total) > 1e-6 {
        return Err(format!(
            "{name}: total_cost {:e}, the pooled lm shortfall sums to {paid_total:e}",
            num(got, "total_cost")
        ));
    }

    // 0122: `new_unexplained_gap` is the indicator's coefficient of the pooled `lm` REFITTED on the
    // wages after the payments (before, nothing checked it here). Plain-std refit, no engine code.
    let mut y_after = y.clone();
    for i in (0..support::N_ROWS).filter(|&i| support::is_target_row(i)) {
        let fair = support::dot(&fit.beta[..k], &fixture.features(i));
        if fair - y[i] > 1e-6 {
            y_after[i] = fair;
        }
    }
    let refit = support::ols(&x, &y_after);
    let gamma_after = refit.beta[k];
    if rel_diff(num(got, "new_unexplained_gap"), gamma_after) > 1e-8 {
        return Err(format!(
            "{name}: new_unexplained_gap {:e}, the refitted pooled indicator is {gamma_after:e}",
            num(got, "new_unexplained_gap")
        ));
    }
    Ok(())
}

/// Field-scoped comparison of a current result against the pre-0118 golden. `Ok(worst)` or the
/// first mismatch. See the module comment for what may differ.
fn compare_scoped(name: &str, want: &Value, got: &Value) -> Result<f64, String> {
    let mut want = want.clone();
    let mut got = got.clone();
    scope_s6_to_s8(name, &mut want, &mut got)?;
    let normalised = NORMALISED_CASES.contains(&name);

    if let Some(meta) = got.get_mut("run_metadata").and_then(Value::as_object_mut) {
        for key in ENGINE_LAYER_METADATA {
            meta.remove(key);
        }
        if normalised {
            if meta.remove("normalization").is_none() {
                return Err("$.run_metadata.normalization missing on a normalised case".into());
            }
        } else if meta.contains_key("normalization") {
            return Err(
                "$.run_metadata.normalization present on a case with no categorical".into(),
            );
        }
    }

    if normalised {
        for (field, aggregate) in [
            ("detailed_explained", "explained_gap"),
            ("detailed_unexplained", "unexplained_gap"),
        ] {
            let old = estimates_of(&want, field);
            let new = estimates_of(&got, field);
            let sum: f64 = new.iter().map(|(_, e)| e).sum();
            let target = want[aggregate].as_f64().unwrap();
            let d = rel_diff(sum, target);
            if d > REL_TOL {
                return Err(format!(
                    "$.{field}: estimates sum to {sum:e}, golden {aggregate} is {target:e} (relative diff {d:e})"
                ));
            }
            for (n, _) in &old {
                if !new.iter().any(|(m, _)| m == n) {
                    return Err(format!(
                        "$.{field}: golden name {n:?} missing from the new vector"
                    ));
                }
            }
            let extra: Vec<&String> = new
                .iter()
                .map(|(m, _)| m)
                .filter(|m| !old.iter().any(|(n, _)| n == *m))
                .collect();
            // One categorical variable (Dept): the only new name is its base level, `Dept_<x>`.
            if extra.len() != 1 || !extra[0].starts_with("Dept_") {
                return Err(format!(
                    "$.{field}: expected exactly the Dept base level as new name, got {extra:?}"
                ));
            }
        }
        for field in NORMALISED_DRIVER_FIELDS {
            want.as_object_mut().unwrap().remove(field);
            got.as_object_mut().unwrap().remove(field);
        }
    }
    compare("$", &want, &got)
}

#[test]
fn null_free_outputs_match_the_pre_0118_engine() {
    let cases = cases();

    if std::env::var("MERIDIAN_PRINT_GOLDEN").as_deref() == Ok("json") {
        for (name, json) in &cases {
            println!("JSON\t{name}\t{json}");
        }
        return;
    }

    let golden = std::fs::read_to_string(golden_path()).expect("golden file present");
    let want: HashMap<&str, &str> = golden
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| l.split_once('\t').expect("name<TAB>json line"))
        .collect();

    assert_eq!(
        want.len(),
        cases.len(),
        "the golden file and the case list must agree on the cases"
    );
    let mut moved = Vec::new();
    for (name, json) in &cases {
        let expected = want
            .get(name.as_str())
            .unwrap_or_else(|| panic!("case {name} has no golden entry"));
        let want_v: Value = serde_json::from_str(expected).expect("golden json parses");
        let got_v: Value = serde_json::from_str(json).expect("result json parses");
        match compare_scoped(name, &want_v, &got_v) {
            Ok(worst) => println!("{name}: worst relative difference {worst:e}"),
            Err(why) => moved.push(format!("{name}: {why}")),
        }
    }
    // 0122 T6: under a range target `original_unexplained_gap` is the MIDPOINT line's, the figure
    // the default case reports, not the mean shortfall to the bound. (The comparator drops the
    // field from both sides for these cases; this is where it is held.)
    let by_name: HashMap<&str, Value> = cases
        .iter()
        .map(|(n, j)| (n.as_str(), serde_json::from_str(j).unwrap()))
        .collect();
    let midpoint = by_name["optimize/noisy/default"]["original_unexplained_gap"]
        .as_f64()
        .unwrap();
    for case in RANGE_TARGET_CASES {
        let got = by_name[case]["original_unexplained_gap"].as_f64().unwrap();
        if rel_diff(got, midpoint) > REL_TOL {
            moved.push(format!(
                "{case}: original_unexplained_gap {got:e} is not the midpoint line's {midpoint:e}"
            ));
        }
    }
    assert!(
        moved.is_empty(),
        "output changed on a null-free file:\n{}\nRe-run with MERIDIAN_PRINT_GOLDEN=json against \
         the pre-0118 engine (8e4e552) to compare.",
        moved.join("\n")
    );
}

// Each gate must be shown to fail (agentic-workflow-principles: a green gate that could not have
// failed is not evidence). These feed `compare_scoped` results it must refuse.
fn tiny_result(unexplained: f64) -> Value {
    serde_json::json!({
        "total_gap": 3.0,
        "explained_gap": 1.0,
        "unexplained_gap": unexplained,
        "detailed_explained": [{"name": "x", "estimate": 1.0}],
        "detailed_unexplained": [{"name": "x", "estimate": 2.0}],
        "run_metadata": {"seed": "1"}
    })
}

#[test]
fn scoped_comparator_refuses_an_aggregate_change() {
    let want = tiny_result(2.0);
    let mut got = tiny_result(2.0 + 1e-6);
    got["run_metadata"]["engine_version"] = serde_json::json!("0.2.0");
    assert!(compare_scoped("plain/other", &want, &got).is_err());
    // and accepts the allowed provenance keys alone
    let mut ok = tiny_result(2.0);
    ok["run_metadata"]["engine_version"] = serde_json::json!("0.2.0");
    ok["run_metadata"]["method"] = serde_json::json!("oaxaca-blinder-mean");
    ok["run_metadata"]["reference_coefficients_used"] = serde_json::json!("Pooled");
    assert!(compare_scoped("plain/other", &want, &ok).is_ok());
}

#[test]
fn scoped_comparator_does_not_exempt_drivers_outside_the_named_case() {
    let want = tiny_result(2.0);
    let mut got = tiny_result(2.0);
    got["detailed_unexplained"][0]["estimate"] = serde_json::json!(2.5);
    assert!(compare_scoped("plain/other", &want, &got).is_err());
}

#[test]
fn scoped_comparator_holds_a_normalised_case_to_adding_up() {
    // A normalised case may change its driver vectors, but they must still add up and may
    // only gain the base level.
    let want = serde_json::json!({
        "explained_gap": 1.0, "unexplained_gap": 2.0,
        "detailed_explained": [{"name": "Dept_B", "estimate": 1.0}],
        "detailed_unexplained": [{"name": "Dept_B", "estimate": 2.0}],
        "run_metadata": {"seed": "1"}
    });
    let good = serde_json::json!({
        "support": {}, "warnings": [],
        "explained_gap": 1.0, "unexplained_gap": 2.0,
        "detailed_explained": [{"name": "Dept_B", "estimate": 0.4}, {"name": "Dept_A", "estimate": 0.6}],
        "detailed_unexplained": [{"name": "Dept_B", "estimate": 1.5}, {"name": "Dept_A", "estimate": 0.5}],
        "run_metadata": {"seed": "1", "normalization": {"applied": true}}
    });
    assert!(compare_scoped("decompose/noisy+dept/pooled", &want, &good).is_ok());
    let mut broken = good.clone();
    broken["detailed_unexplained"][1]["estimate"] = serde_json::json!(0.6);
    assert!(compare_scoped("decompose/noisy+dept/pooled", &want, &broken).is_err());
    let mut extra = good.clone();
    extra["detailed_explained"]
        .as_array_mut()
        .unwrap()
        .push(serde_json::json!({"name": "Other", "estimate": 0.0}));
    assert!(compare_scoped("decompose/noisy+dept/pooled", &want, &extra).is_err());
}

// ---- the S6-S8 gates must be shown to fail ----------------------------------------------------

fn s7_golden_and_result(ratio: f64, defensible_message: Option<&str>) -> (Value, Value) {
    // One target row, fair 100, z half-width 10, df chosen so t/z = `ratio` is applied by the
    // caller when building the result's bounds.
    let want = serde_json::json!({
        "adjustments": [{
            "index": 3, "fair_wage": 100.0, "current_wage": 90.0, "new_wage": 95.0,
            "fair_wage_lower_bound": 90.0, "fair_wage_upper_bound": 110.0,
            "is_defensible": true,
            "defensibility_message": "Wage is within or above the calculated fair range."
        }],
        "model_coefficients": [{"name": "a"}, {"name": "b"}],
        "original_gap": 5.0, "new_gap": 4.0,
        "original_unexplained_gap": 3.0, "new_unexplained_gap": 2.0
    });
    let half = 10.0 * ratio;
    let mut got = want.clone();
    // defensibility reports the opposite sign now (0122 T7)
    got["original_gap"] = serde_json::json!(-5.0);
    got["new_gap"] = serde_json::json!(-4.0);
    got["original_unexplained_gap"] = serde_json::json!(-3.0);
    got["adjustments"][0]["fair_wage_lower_bound"] = serde_json::json!(100.0 - half);
    got["adjustments"][0]["fair_wage_upper_bound"] = serde_json::json!(100.0 + half);
    got["adjustments"][0]["extrapolated"] = serde_json::json!(false);
    if let Some(m) = defensible_message {
        got["adjustments"][0]["defensibility_message"] = serde_json::json!(m);
    }
    got["support"] = serde_json::json!({});
    got["warnings"] = serde_json::json!([]);
    got["interval"] = serde_json::json!({"degrees_of_freedom": 58, "confidence_level": 0.95});
    for key in ADDED_BY_0122 {
        got[key] = serde_json::Value::Null;
    }
    got["adjustments"][0]["source"] = serde_json::json!("Compared");
    got["adjustments"][0]["range_position"] = serde_json::json!("Inside");
    got["adjustments"][0]["range_position_before"] = serde_json::json!("Below");
    (want, got)
}

#[test]
fn s7_comparator_accepts_t_bounds_and_refuses_z_bounds() {
    // 60 reference rows, 2 coefficients -> 58 residual df: t/z is only 1.0206 there, yet the
    // difference still moves a bound by more than the 1e-9 tolerance.
    let r = t_over_z(0.95, 58.0);
    assert!(r > 1.02, "t(58)/z must exceed 1: {r}");
    let (want, got) = s7_golden_and_result(r, None);
    assert!(compare_scoped("defensibility/self", &want, &got).is_ok());
    // The golden's own z bounds (ratio 1) are what a z implementation would still return.
    let (want, got) = s7_golden_and_result(1.0, None);
    assert!(
        compare_scoped("defensibility/self", &want, &got).is_err(),
        "z bounds must be refused where df is small"
    );
}

#[test]
fn s7_comparator_refuses_a_missing_block_and_a_wrong_verdict_message() {
    let r = t_over_z(0.95, 58.0);
    let (want, mut got) = s7_golden_and_result(r, None);
    got.as_object_mut().unwrap().remove("support");
    assert!(compare_scoped("defensibility/self", &want, &got).is_err());
    let (want, got) = s7_golden_and_result(
        r,
        Some("Wage is 1.00 below the defensible lower bound (9.00)."),
    );
    assert!(compare_scoped("defensibility/self", &want, &got).is_err());
}

#[test]
fn s7_comparator_refuses_a_frontier_p_value_that_is_not_student_t() {
    use statrs::distribution::{ContinuousCDF, Normal, StudentsT};
    let dof = (support::N_ROWS - 4) as f64;
    let t = 2.0;
    let p_t = 2.0 * StudentsT::new(0.0, 1.0, dof).unwrap().cdf(-t);
    let p_z = 2.0 * Normal::new(0.0, 1.0).unwrap().cdf(-t);
    let point = |p: f64| {
        serde_json::json!([{
            "budget": 0.0, "t_statistic": t, "p_value": p, "is_significant": p < 0.05,
            "group_coefficient": 1.0, "degrees_of_freedom": dof as i64,
            "confidence_level": 0.95
        }])
    };
    let want = serde_json::json!([{"budget": 0.0, "t_statistic": t, "p_value": p_z, "is_significant": true}]);
    assert!(compare_scoped("frontier/self", &want, &point(p_t)).is_ok());
    assert!(
        compare_scoped("frontier/self", &want, &point(p_z)).is_err(),
        "a normal-theory p-value must be refused"
    );
}
