//! 0118-MERIDIAN: Fixture F's committed CSV and its stated properties.
//!
//! `fixtures/0118-fixture-f.csv` is the target-row-blank-free ("exact") variant the app phase
//! copies. It is generated by `support::FixtureF`; this test fails if the committed file and
//! the builder ever drift apart. To regenerate after an intentional change:
//!
//!   MERIDIAN_WRITE_FIXTURE=1 cargo test -p pay-equity-engine --test rows_fixture_file_test
//!
//! The file the spec asks for is the "target-row-blank" variant of F. The committed file blanks
//! the Experience cell of one target employee (ordinal 13) so the app can run V9 on it as is;
//! the same file with that one cell filled in is `FixtureF::exact()`.

mod support;

use std::collections::BTreeSet;
use support::{formula, is_target_row, shortfall, Col, FixtureF, N_ROWS, REFERENCE, TARGET};

/// The ordinal of the blank cell in the committed file: a target employee in the middle.
const BLANK_TARGET_ROW: usize = 13;

fn committed_variant() -> FixtureF {
    FixtureF::exact().blank(BLANK_TARGET_ROW, Col::Experience)
}

fn path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/0118-fixture-f.csv")
}

#[test]
fn the_committed_csv_is_what_the_builder_produces() {
    let want = committed_variant().csv();
    if std::env::var("MERIDIAN_WRITE_FIXTURE").as_deref() == Ok("1") {
        std::fs::create_dir_all(path().parent().unwrap()).unwrap();
        std::fs::write(path(), &want).unwrap();
    }
    let got = std::fs::read_to_string(path()).expect(
        "fixtures/0118-fixture-f.csv must exist (regenerate with MERIDIAN_WRITE_FIXTURE=1)",
    );
    assert_eq!(got, want, "committed fixture drifted from FixtureF");
    assert!(got.starts_with("Name,Salary,Gender,Experience,Level\n"));
    assert_eq!(got.lines().count(), N_ROWS + 1);
}

#[test]
fn fixture_f_has_the_properties_the_spec_states() {
    let f = FixtureF::exact();
    assert_eq!(f.rows.len(), N_ROWS);

    // Unique names.
    let names: BTreeSet<&str> = f.rows.iter().map(|r| r.name.as_str()).collect();
    assert_eq!(names.len(), N_ROWS);

    // Groups interleaved; the last raw row is a reference employee.
    assert_eq!(f.reference_ordinals().len(), 60);
    assert_eq!(f.target_ordinals().len(), 40);
    assert!(!is_target_row(N_ROWS - 1));
    assert_eq!(f.rows[N_ROWS - 1].gender, REFERENCE);
    let last_target = *f.target_ordinals().last().unwrap();
    assert_eq!(last_target, 98);
    assert_eq!(f.rows[last_target].gender, TARGET);

    // Reference rows are paid exactly the formula.
    for i in f.reference_ordinals() {
        let r = &f.rows[i];
        assert_eq!(r.salary as f64, formula(r.experience, r.level), "row {i}");
    }

    // Target rows are paid below the formula by a distinct, non-monotone amount; some are
    // overpaid; the last target employee is underpaid.
    let shortfalls: Vec<i64> = f
        .target_ordinals()
        .iter()
        .map(|&i| formula(f.rows[i].experience, f.rows[i].level) as i64 - f.rows[i].salary)
        .collect();
    assert_eq!(shortfalls, (0..40).map(shortfall).collect::<Vec<_>>());
    let distinct: BTreeSet<i64> = shortfalls.iter().copied().collect();
    assert_eq!(distinct.len(), 40, "every shortfall is distinct");
    let ups = shortfalls.windows(2).filter(|w| w[1] > w[0]).count();
    assert!(ups > 5 && ups < 35, "neither monotone up nor down: {ups}");
    assert_eq!(
        shortfalls.iter().filter(|&&s| s < 0).count(),
        9,
        "nine overpaid employees"
    );
    assert!(shortfalls.iter().all(|&s| s != 0));
    assert!(
        *shortfalls.last().unwrap() > 0,
        "last target employee is underpaid"
    );

    // Raw ordinal and group-local position differ for every target employee after the first,
    // so a raw-position mapping cannot coincide with a group-local one.
    let target = f.target_ordinals();
    assert!(target.iter().enumerate().skip(1).all(|(k, &i)| i != k));
    let reference = f.reference_ordinals();
    assert!(reference.iter().enumerate().skip(1).any(|(k, &i)| i != k));

    // The optional columns exist in every group.
    for group in [f.reference_ordinals(), f.target_ordinals()] {
        let depts: BTreeSet<&str> = group.iter().map(|&i| f.rows[i].dept).collect();
        assert_eq!(depts.len(), 3, "all three Dept levels in each group");
    }
}

#[test]
fn the_noisy_variant_differs_only_in_the_reference_rows() {
    let exact = FixtureF::exact();
    let noisy = FixtureF::noisy();
    for i in 0..N_ROWS {
        if is_target_row(i) {
            assert_eq!(exact.rows[i].salary, noisy.rows[i].salary, "target row {i}");
        }
    }
    let diffs = exact
        .reference_ordinals()
        .iter()
        .filter(|&&i| exact.rows[i].salary != noisy.rows[i].salary)
        .count();
    assert!(diffs > 40, "{diffs} reference rows carry noise");
    // Known residual, bounded.
    for &i in &noisy.reference_ordinals() {
        assert!((noisy.rows[i].salary - exact.rows[i].salary).abs() <= 240);
    }
}
